### ISSUE TITLE
White page shown for react-thee-fiber package

### ISSUE THREAD

**Issue by garethx** [codesandbox/dependency-seo-pages#11]
Only a white page is shown when visiting the incorrectly spelled 'react-thee-fiber' package: https://dependency.csb.dev/package/react-thee-fiber

I think it's because it's not a package on npm, but there is one search result on CSB for it: https://codesandbox.io/search?refinementList%5Bnpm_dependencies.dependency%5D%5B0%5D=react-thee-fiber&page=1&configure%5BhitsPerPage%5D=12

**Comment by garethx** [comment]
Same happens with https://dependency.csb.dev/package/@codesandbox/components but for different reasons maybe? At least, errors in console seem different.

**Comment by SaraVieira** [comment]
Both fixed :)
