### ISSUE TITLE
Long descriptions sometimes underlap creator avatar + technology icon

### ISSUE THREAD

**Issue by garethx** [codesandbox/dependency-seo-pages#13]
![Screenshot 2020-03-18 at 14 06 02](https://user-images.githubusercontent.com/1830035/76969119-df55c980-6921-11ea-9a7b-3cc4d3ad85f7.png)

**Comment by SaraVieira** [comment]
Fixed! 🎉

![Screenshot 2020-04-14 at 18 28 06](https://user-images.githubusercontent.com/1051509/79249558-bae80100-7e7d-11ea-89bc-1b9139a4cc6f.png)
