### ISSUE TITLE
On-demand creation of dependency pages doesn't work with CSB URL

### ISSUE THREAD

**Issue by garethx** [codesandbox/dependency-seo-pages#15]
It looks like instances where the package isn’t in the pre-cached list, so it’s a 404 and the page should be created on-demand isn’t working when using the csb URL e.g. https://codesandbox.io/examples/package/vuejs-progress-bar black screen, but https://dependency.csb.dev/package/vuejs-progress-bar works

**Comment by SaraVieira** [comment]
https://codesandbox.io/examples/package/vuejs-progress-bar

YAAAY
