### ISSUE TITLE
404 page isn't shown when using CSB URL

### ISSUE THREAD

**Issue by garethx** [codesandbox/dependency-seo-pages#16]
404s show a black screen and not the 404 screen. e.g. https://codesandbox.io/examples/package/vuejs-hfghgfhfghfg but it works on .dev url https://dependency.csb.dev/package/vuejs-hfghgfhfghfg

**Comment by garethx** [comment]
Ives comments: that's because of the example/ pretending. I think in the gatsby app we need to prepend with examples/ as well.

**Comment by SaraVieira** [comment]
Fixed with a lot of sweat and tears

https://codesandbox.io/examples/package/vuesjhdka
