### ISSUE TITLE
Meta data display issues for dependencies with @ / in title

### ISSUE THREAD

**Issue by garethx** [codesandbox/dependency-seo-pages#6]
E.g.
https://dependency.csb.dev/package/@nestjs/websockets
https://dependency.csb.dev/package/@angular/common

![Screenshot 2020-02-26 at 12 03 00](https://user-images.githubusercontent.com/1830035/75343425-5bfc0780-5890-11ea-9fc9-f3ccdd5e83f5.png)
![Screenshot 2020-02-26 at 12 04 33](https://user-images.githubusercontent.com/1830035/75343426-5c949e00-5890-11ea-9905-39fb27d6119e.png)

**Comment by SaraVieira** [comment]
Some don't have size so I only show when I am able to fetch the size and the other issue is fixed :)
