### ISSUE TITLE
About panel overlaps 3rd column of results at some screen widths

### ISSUE THREAD

**Issue by garethx** [codesandbox/dependency-seo-pages#9]
I tried to solve this in an earlier PR by adjusting the breakpoints, but I'm not sure how to alter the number of columns it decides to use. But, the about panel overlaps the 3rd column of results at some screen widths, see https://www.loom.com/share/7d33fe51c7dc4857853a4fb89f81ef34

**Comment by SaraVieira** [comment]
Fixed with next button fix
